// Generated by typescript generator

import { Operation } from "postchain-client";
import { QueryObject } from "postchain-client";

export function getTicketChainRidQueryObject(): QueryObject<Buffer | null> {
	return { name: "get_ticket_chain_rid", args: undefined };
}

export function initTicketingOperation(myPubkey: Buffer,
	ticketChainConfig: Buffer): Operation {
	return { name: "init_ticketing", args: [myPubkey,
	ticketChainConfig] }
}
