// Generated by typescript generator

export enum BlockchainState {
	RUNNING,
	PAUSED,
	REMOVED,
	IMPORTING,
	ARCHIVED
}

export enum ContainerResourceLimitType {
	container_units,
	max_blockchains,
	extra_storage
}

export enum ContainerState {
	RUNNING,
	STOPPED
}

export enum NodeCapabilityType {
	SYSTEM_MANAGED,
	ETHEREUM_BRIDGE,
	ETHEREUM_TESTNET_BRIDGE,
	BCS_BRIDGE,
	BCS_TESTNET_BRIDGE,
	POLYGON_BRIDGE,
	POLYGON_TESTNET_BRIDGE
}

export enum ProviderTier {
	COMMUNITY_NODE_PROVIDER,
	NODE_PROVIDER
}

export enum ProviderQuotaType {
	max_actions_per_day,
	max_nodes,
	max_containers
}

export type Blockchain = {
	rid: Buffer;
	name: string;
	system: boolean;
	state: BlockchainState;
};

export type BlockchainConfiguration = {
	blockchain: number;
	height: number;
	data: Buffer;
};

export type BlockchainConfigurationOptions = {
	blockchain: number;
	height: number;
	suppress_special_transaction_validation: boolean;
};

export type Provider = {
	pubkey: Buffer;
	name: string;
	url: string;
	active: boolean;
	tier: ProviderTier;
	system: boolean;
};

export type ProviderQuota = {
	tier: ProviderTier;
	provider_quota_type: ProviderQuotaType;
	value: number;
};

export type VoterSet = {
	name: string;
	threshold: number;
};

export type ClusterQuotaData = {
	cluster_units: number;
	extra_storage: number;
};

export type RegisterNodeData = {
	pubkey: Buffer;
	host: string;
	port: number;
	api_url: string;
	clusters: string[];
	cluster_units: number;
	territory: string;
	extra_storage: number;
};

export type ReplaceNodeData = {
	old_node_key: Buffer;
	new_node_key: Buffer;
	new_host: string | null;
	new_port: number | null;
	new_api_url: string | null;
	new_cluster_units: number | null;
	new_territory: string | null;
	new_extra_storage: number | null;
};

export type UpdateNodeData = {
	pubkey: Buffer;
	host: string | null;
	port: number | null;
	api_url: string | null;
	cluster_units: number | null;
	territory: string | null;
	extra_storage: number | null;
};

export type ProviderInfo = {
	pubkey: Buffer;
	name: string;
	url: string;
};
