image: node:18-slim

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

deploy:
  stage: deploy
  script:
    - npm install
    - npm run build
  environment: dev
